name: Debian Install Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: sudo apt-get install -y libarchive-tools genisoimage

    - name: Build Images
      run: ./mkcd.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with: 
        name: rittdev-iso
        path: |
          rittdev-stable-amd64.iso
          rittdev-stable-i386.iso
          rittdev-unstable-amd64.iso
          rittdev-unstable-i386.iso
